// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gallery.Models;

public partial class User
{
    public string Username { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string DisplayName { get; set; }

    public string Role { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int Id { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();
}